[package]
name = "multiaddr"
version = "0.1.0"
authors = ["Nick Hamann <nick@wabbo.org>"]

[dependencies]
varint = { git = "https://github.com/nham/Varint-rs.git", branch = "add_impl" }
rust-multihash = { git = "https://github.com/nham/rust-multihash.git" }
